
name: 'dataton_puebla'
version: '1.0.0'
config-version: 2

profile: 'dataton_puebla'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dataton_puebla:
    # Configuración predeterminada para los modelos
    staging:
      +materialized: view
