drop table if exists nice-opus-462200-h0.ydata.R_1_INSTITUCION_COMPLETA;
create table nice-opus-462200-h0.ydata.R_1_INSTITUCION_COMPLETA AS
with final as (
  select 
    TRIM(REGEXP_REPLACE(tva.INSTITUCION, r'\s+', ' ')) INSTITUCION,
    tva.ENTIDAD_CD,
    TRIM(REGEXP_REPLACE(tva.MUNICIPIO, r'\s+', ' ')) MUNICIPIO,
    tva.DECLARACION_ANIO,
    sum(tva.SUMA_VALOR_ADQUISICION) SUMA_VALOR_ADQUISICION,
    sum(tva.BIEN_INMUEBLE_VALOR) BIEN_INMUEBLE_VALOR,
    sum(tva.BIEN_MUEBLE_VALOR) BIEN_MUEBLE_VALOR,
    sum(tva.VEHICULO_VALOR) VEHICULO_VALOR,
    sum(tva.TOTAL_DECLARACIONES) TOTAL_DECLARACIONES,
    sum(si.SERVIDORES_INDIVIDUALES) SERVIDORES_INDIVIDUALES,
    sum(si.EMPLEOS_CARGO_COMISION) EMPLEOS_CARGO_COMISION,
    sum(ii.REMUNERACION_ANUAL_CARGO_PUBLICO) REMUNERACION_ANUAL_CARGO_PUBLICO,
    sum(ii.TOTAL_INGRESOS_MENSUALES_NETOS) TOTAL_INGRESOS_MENSUALES_NETOS,
    sum(ii.INGRESO_ANUAL_NETO_DECLARANTE) INGRESO_ANUAL_NETO_DECLARANTE
  FROM nice-opus-462200-h0.ydata.AN_1_INSTITUCION_INGRESOS ii
  FULL OUTER JOIN nice-opus-462200-h0.ydata.AN_2_TOTAL_VALOR_ADQUISICION tva
  ON TRIM(REGEXP_REPLACE(tva.INSTITUCION, r'\s+', ' ')) = TRIM(REGEXP_REPLACE(ii.INSTITUCION, r'\s+', ' ')) 
  AND tva.ENTIDAD_CD = ii.ENTIDAD_CD
  AND TRIM(REGEXP_REPLACE(tva.MUNICIPIO, r'\s+', ' ')) = TRIM(REGEXP_REPLACE(ii.MUNICIPIO, r'\s+', ' '))
  AND tva.DECLARACION_ANIO = ii.DECLARACION_ANIO
  FULL OUTER JOIN nice-opus-462200-h0.ydata.AN_3_INSTITUCIONES_SERVIDORES_INDIVIDUALES si
  ON TRIM(REGEXP_REPLACE(tva.INSTITUCION, r'\s+', ' ')) = TRIM(REGEXP_REPLACE(si.INSTITUCION, r'\s+', ' ')) 
  AND tva.ENTIDAD_CD = si.ENTIDAD_CD
  AND TRIM(REGEXP_REPLACE(tva.MUNICIPIO, r'\s+', ' ')) = TRIM(REGEXP_REPLACE(ii.MUNICIPIO, r'\s+', ' '))
  AND tva.DECLARACION_ANIO = si.DECLARACION_ANIO
  group by 1,2,3,4
  order by 1,2,3,4
) 
select 
    INSTITUCION, NOMBRE DE LA INSTITUCION
    ENTIDAD_CD, CODIGO DE ESTADO DE LA INSTITUCION
    MUNICIPIO,  MUNICIPIO DE LA INSTITUCION
    DECLARACION_ANIO, ANO DECLARACION
    IFNULL(SUMA_VALOR_ADQUISICION, 0) SUMA_VALOR_ADQUISICION, SUMA DE BIEN_INMUEBLE_VALOR + BIEN_INMUEBLE_VALOR + VEHICULO_VALOR
    IFNULL(BIEN_INMUEBLE_VALOR, 0) BIEN_INMUEBLE_VALOR, SUMA DE BIEN_INMUEBLE_VALOR DE LAS DECLARACIONES DE LA INSTITUCION
    IFNULL(BIEN_MUEBLE_VALOR, 0) BIEN_MUEBLE_VALOR,  SUMA DE BIEN_MUEBLE_VALOR DE LAS DECLARACIONES DE LA INSTITUCION
    IFNULL(VEHICULO_VALOR, 0) VEHICULO_VALOR, SUMA DE VEHICULO_VALOR DE LAS DECLARACIONES DE LA INSTITUCION
    IFNULL(TOTAL_DECLARACIONES, 0) TOTAL_DECLARACIONES, CONTEO DE LAS DECLARACIONES DE LA INSTITUCION
    IFNULL(SERVIDORES_INDIVIDUALES, 0) SERVIDORES_INDIVIDUALES, CONTEO DE LOS SERVIDORES INDIVIDUALES UNICOS DETECTADOS EN LA INSTITUCION
    IFNULL(EMPLEOS_CARGO_COMISION, 0) EMPLEOS_CARGO_COMISION, CONTEO DE LOS EMPLEOS O CARGOS DIFERENTES EN LA INSTITUCION
    IFNULL(REMUNERACION_ANUAL_CARGO_PUBLICO, 0) REMUNERACION_ANUAL_CARGO_PUBLICO, SUMA DE REMUNERACION_ANUAL_CARGO_PUBLICO DE LAS DECLARACIONES DE LA INSTITUCION
    IFNULL(TOTAL_INGRESOS_MENSUALES_NETOS, 0) TOTAL_INGRESOS_MENSUALES_NETOS, SUMA DE TOTAL_INGRESOS_MENSUALES_NETOS DE LAS DECLARACIONES DE LA INSTITUCION
    IFNULL(INGRESO_ANUAL_NETO_DECLARANTE, 0) INGRESO_ANUAL_NETO_DECLARANTE, SUMA DE INGRESO_ANUAL_NETO_DECLARANTE DE LAS DECLARACIONES DE LA INSTITUCION
from final 


