drop table if exists nice-opus-462200-h0.ydata.R1_DECLARACION_INDIVIDUAL;
create table nice-opus-462200-h0.ydata.R1_DECLARACION_INDIVIDUAL AS
with total as (
  select 
  coalesce(dva.DECLARACION_ID, di.DECLARACION_ID) as DECLARACION_ID,
  coalesce(dva.INSTITUCION, di.INSTITUCION) as INSTITUCION,
  coalesce(dva.ENTIDAD_CD, di.ENTIDAD_CD) as ENTIDAD_CD,
  coalesce(dva.MUNICIPIO, di.MUNICIPIO) as MUNICIPIO,
  coalesce(dva.DECLARACION_ANIO, di.DECLARACION_ANIO) as DECLARACION_ANIO,
  ifnull(dva.SUMA_VALOR_ADQUISICION, 0) SUMA_VALOR_ADQUISICION,
  ifnull(dva.BIEN_INMUEBLE_VALOR, 0) BIEN_INMUEBLE_VALOR,
  ifnull(dva.BIEN_MUEBLE_VALOR, 0) BIEN_MUEBLE_VALOR,
  ifnull(dva.VEHICULO_VALOR, 0) VEHICULO_VALOR,
  ifnull(di.REMUNERACION_ANUAL_CARGO_PUBLICO, 0) REMUNERACION_ANUAL_CARGO_PUBLICO,
  ifnull(di.TOTAL_INGRESOS_MENSUALES_NETOS, 0) TOTAL_INGRESOS_MENSUALES_NETOS,
  ifnull(di.INGRESO_ANUAL_NETO_DECLARANTE, 0) INGRESO_ANUAL_NETO_DECLARANTE
from nice-opus-462200-h0.ydata.R_1_DECLARACION_VALOR_ADQUISICION dva
full outer join nice-opus-462200-h0.ydata.R_1_DECLARACION_INGRESOS di
on dva.DECLARACION_ID = di.DECLARACION_ID
), add_servidor as (
  select distinct t.*, 
  IF(sp.SERVIDOR_PUBLICO_CURP IN ('None',''), NULL, sp.SERVIDOR_PUBLICO_CURP) AS CURP,
  IF(sp.NOMBRE IN ('None',''), NULL, sp.NOMBRE) AS NOMBRE,
  IF(sp.PRIMER_APELLIDO IN ('None',''), NULL, sp.PRIMER_APELLIDO) AS PRIMER_APELLIDO,
  IF(sp.SEGUNDO_APELLIDO IN ('None',''), NULL, sp.SEGUNDO_APELLIDO) AS SEGUNDO_APELLIDO,
  IF(sp.RFC_COMPLETO IN ('None',''), NULL, sp.RFC_COMPLETO) AS RFC_COMPLETO,
  IF(sp.CORREO_INSTITUCIONAL IN ('None',''), NULL, sp.CORREO_INSTITUCIONAL) AS CORREO_INSTITUCIONAL,
  IF(sp.CORREO_PERSONAL IN ('None',''), NULL, sp.CORREO_PERSONAL) AS CORREO_PERSONAL
from total t
left join nice-opus-462200-h0.ydata.C_S1_SERVIDOR_PUBLICO sp
on t.DECLARACION_ID = sp.DECLARACION_ID
)
select *
from add_servidor