drop table if exists nice-opus-462200-h0.ydata.AN_3_INSTITUCIONES_SERVIDORES_INDIVIDUALES;

create table if not exists nice-opus-462200-h0.ydata.AN_3_INSTITUCIONES_SERVIDORES_INDIVIDUALES AS
with generar_llave as (
  select 
  concat(
    CURP, '-',
    NOMBRE, '-',
    PRIMER_APELLIDO, '-',
    SEGUNDO_APELLIDO, '-',
    RFC_COMPLETO, '-',
    CORREO_INSTITUCIONAL, '-',
    CORREO_PERSONAL, '-',
    INSTITUCION, '-',
    EMPLEO_CARGO_COMISION
  ) llave
  from `nice-opus-462200-h0.ydata.AN_1_SERVIDORES_INDIVIDUALES_LLAVE`
), add_campos_faltantes as (
select d.*, 
  concat(
      d.SERVIDOR_PUBLICO_CURP, '-',
      sp.NOMBRE, '-',
      sp.PRIMER_APELLIDO, '-',
      sp.SEGUNDO_APELLIDO, '-',
      sp.RFC_COMPLETO, '-',
      sp.CORREO_INSTITUCIONAL, '-',
      sp.CORREO_PERSONAL, '-',
      d.INSTITUCION, '-',
      ecc.EMPLEO_CARGO_COMISION
    ) SERVIDOR_INDIVIDUAL,
  extract(YEAR FROM d.FECHA_ACTUALIZACION) DECLARACION_ANIO,
  ecc.EMPLEO_CARGO_COMISION,
  ecc.MUNICIPIO,
  CASE
      WHEN UPPER(ENTIDAD) IN ('AGUASCALIENTES') THEN 'MX-AGU'
      WHEN UPPER(ENTIDAD) IN ('BAJA CALIFORNIA') THEN 'MX-BCN'
      WHEN UPPER(ENTIDAD) IN ('BAJA CALIFORNIA SUR') THEN 'MX-BCS'
      WHEN UPPER(ENTIDAD) IN ('CAMPECHE') THEN 'MX-CAM'
      WHEN UPPER(ENTIDAD) IN ('COAHUILA DE ZARAGOZA', 'COAHUILA') THEN 'MX-COA'
      WHEN UPPER(ENTIDAD) IN ('COLIMA') THEN 'MX-COL'
      WHEN UPPER(ENTIDAD) IN ('CHIAPAS') THEN 'MX-CHP'
      WHEN UPPER(ENTIDAD) IN ('CHIHUAHUA') THEN 'MX-CHH'
      WHEN UPPER(ENTIDAD) IN ('CIUDAD DE MEXICO','DISTRITO FEDERAL', 'CIUDAD DE MÉXICO') THEN 'MX-CMX'
      WHEN UPPER(ENTIDAD) IN ('DURANGO') THEN 'MX-DUR'
      WHEN UPPER(ENTIDAD) IN ('GUANAJUATO') THEN 'MX-GUA'
      WHEN UPPER(ENTIDAD) IN ('GUERRERO') THEN 'MX-GRO'
      WHEN UPPER(ENTIDAD) IN ('HIDALGO') THEN 'MX-HID'
      WHEN UPPER(ENTIDAD) IN ('JALISCO') THEN 'MX-JAL'
      WHEN UPPER(ENTIDAD) IN ('MEXICO','ESTADO DE MEXICO', 'MÉXICO', 'ESTADO DE MÈXICO', 'ESTADO DE MÉXICO') THEN 'MX-MEX'
      WHEN UPPER(ENTIDAD) IN ('MICHOACAN','MICHOACAN DE OCAMPO', 'MICHOACÁN DE OCAMPO') THEN 'MX-MIC'
      WHEN UPPER(ENTIDAD) IN ('MORELOS') THEN 'MX-MOR'
      WHEN UPPER(ENTIDAD) IN ('NAYARIT') THEN 'MX-NAY'
      WHEN UPPER(ENTIDAD) IN ('NUEVO LEON', 'NUEVO LEÓN') THEN 'MX-NLE'
      WHEN UPPER(ENTIDAD) IN ('OAXACA') THEN 'MX-OAX'
      WHEN UPPER(ENTIDAD) IN ('PUEBLA') THEN 'MX-PUE'
      WHEN UPPER(ENTIDAD) IN ('QUERETARO', 'QUERÉTARO') THEN 'MX-QUE'
      WHEN UPPER(ENTIDAD) IN ('QUINTANA ROO') THEN 'MX-ROO'
      WHEN UPPER(ENTIDAD) IN ('SAN LUIS POTOSI', 'SAN LUIS POTOSÍ') THEN 'MX-SLP'
      WHEN UPPER(ENTIDAD) IN ('SINALOA') THEN 'MX-SIN'
      WHEN UPPER(ENTIDAD) IN ('SONORA') THEN 'MX-SON'
      WHEN UPPER(ENTIDAD) IN ('TABASCO') THEN 'MX-TAB'
      WHEN UPPER(ENTIDAD) IN ('TAMAULIPAS') THEN 'MX-TAM'
      WHEN UPPER(ENTIDAD) IN ('TLAXCALA') THEN 'MX-TLA'
      WHEN UPPER(ENTIDAD) IN ('VERACRUZ','VERACRUZ DE IGNACIO DE LA LLAVE') THEN 'MX-VER'
      WHEN UPPER(ENTIDAD) IN ('YUCATAN', 'YUCATÁN') THEN 'MX-YUC'
      WHEN UPPER(ENTIDAD) IN ('ZACATECAS') THEN 'MX-ZAC'
        ELSE 'NO_APLICA'
    END AS ENTIDAD_CD
from nice-opus-462200-h0.ydata.C_S1_DECLARACION d
join nice-opus-462200-h0.ydata.C_S1_SERVIDOR_PUBLICO sp
  on d.DECLARACION_ID = sp.DECLARACION_ID
join nice-opus-462200-h0.ydata.C_S1_EMPLEO_CARGO_COMISION ecc 
  on d.DECLARACION_ID = ecc.DECLARACION_ID
)
select 
  INSTITUCION,
  ENTIDAD_CD,
  MUNICIPIO,
  DECLARACION_ANIO,
  count(distinct SERVIDOR_INDIVIDUAL) SERVIDORES_INDIVIDUALES,
  count(distinct EMPLEO_CARGO_COMISION) EMPLEOS_CARGO_COMISION
from add_campos_faltantes
group by 1,2,3,4;