drop table if exists nice-opus-462200-h0.ydata.AN_2_TOTAL_VALOR_ADQUISICION;

create table if not exists nice-opus-462200-h0.ydata.AN_2_TOTAL_VALOR_ADQUISICION 
AS
with add_normalize_entidad as (
  SELECT 
    INSTITUCION,
    CASE
      WHEN UPPER(ENTIDAD) IN ('AGUASCALIENTES') THEN 'MX-AGU'
      WHEN UPPER(ENTIDAD) IN ('BAJA CALIFORNIA') THEN 'MX-BCN'
      WHEN UPPER(ENTIDAD) IN ('BAJA CALIFORNIA SUR') THEN 'MX-BCS'
      WHEN UPPER(ENTIDAD) IN ('CAMPECHE') THEN 'MX-CAM'
      WHEN UPPER(ENTIDAD) IN ('COAHUILA DE ZARAGOZA', 'COAHUILA') THEN 'MX-COA'
      WHEN UPPER(ENTIDAD) IN ('COLIMA') THEN 'MX-COL'
      WHEN UPPER(ENTIDAD) IN ('CHIAPAS') THEN 'MX-CHP'
      WHEN UPPER(ENTIDAD) IN ('CHIHUAHUA') THEN 'MX-CHH'
      WHEN UPPER(ENTIDAD) IN ('CIUDAD DE MEXICO','DISTRITO FEDERAL', 'CIUDAD DE MÉXICO') THEN 'MX-CMX'
      WHEN UPPER(ENTIDAD) IN ('DURANGO') THEN 'MX-DUR'
      WHEN UPPER(ENTIDAD) IN ('GUANAJUATO') THEN 'MX-GUA'
      WHEN UPPER(ENTIDAD) IN ('GUERRERO') THEN 'MX-GRO'
      WHEN UPPER(ENTIDAD) IN ('HIDALGO') THEN 'MX-HID'
      WHEN UPPER(ENTIDAD) IN ('JALISCO') THEN 'MX-JAL'
      WHEN UPPER(ENTIDAD) IN ('MEXICO','ESTADO DE MEXICO', 'MÉXICO', 'ESTADO DE MÈXICO', 'ESTADO DE MÉXICO') THEN 'MX-MEX'
      WHEN UPPER(ENTIDAD) IN ('MICHOACAN','MICHOACAN DE OCAMPO', 'MICHOACÁN DE OCAMPO') THEN 'MX-MIC'
      WHEN UPPER(ENTIDAD) IN ('MORELOS') THEN 'MX-MOR'
      WHEN UPPER(ENTIDAD) IN ('NAYARIT') THEN 'MX-NAY'
      WHEN UPPER(ENTIDAD) IN ('NUEVO LEON', 'NUEVO LEÓN') THEN 'MX-NLE'
      WHEN UPPER(ENTIDAD) IN ('OAXACA') THEN 'MX-OAX'
      WHEN UPPER(ENTIDAD) IN ('PUEBLA') THEN 'MX-PUE'
      WHEN UPPER(ENTIDAD) IN ('QUERETARO', 'QUERÉTARO') THEN 'MX-QUE'
      WHEN UPPER(ENTIDAD) IN ('QUINTANA ROO') THEN 'MX-ROO'
      WHEN UPPER(ENTIDAD) IN ('SAN LUIS POTOSI', 'SAN LUIS POTOSÍ') THEN 'MX-SLP'
      WHEN UPPER(ENTIDAD) IN ('SINALOA') THEN 'MX-SIN'
      WHEN UPPER(ENTIDAD) IN ('SONORA') THEN 'MX-SON'
      WHEN UPPER(ENTIDAD) IN ('TABASCO') THEN 'MX-TAB'
      WHEN UPPER(ENTIDAD) IN ('TAMAULIPAS') THEN 'MX-TAM'
      WHEN UPPER(ENTIDAD) IN ('TLAXCALA') THEN 'MX-TLA'
      WHEN UPPER(ENTIDAD) IN ('VERACRUZ','VERACRUZ DE IGNACIO DE LA LLAVE') THEN 'MX-VER'
      WHEN UPPER(ENTIDAD) IN ('YUCATAN', 'YUCATÁN') THEN 'MX-YUC'
      WHEN UPPER(ENTIDAD) IN ('ZACATECAS') THEN 'MX-ZAC'
        ELSE 'NO_APLICA'
    END AS ENTIDAD_CD,
    MUNICIPIO,
    DECLARACION_ANIO,
    SUMA_VALOR_ADQUISICION,
    BIEN_INMUEBLE_VALOR,
    BIEN_MUEBLE_VALOR,
    VEHICULO_VALOR,
    TOTAL_DECLARACIONES, 
    PERCENT_INMUEBLE_VALOR,
    PERCENT_MUEBLE_VALOR,
    PERCENT_VEHICULO_VALOR
  FROM `nice-opus-462200-h0.ydata.AN_1_TOTAL_VALOR_ADQUISICION`
  where ENTIDAD is not null and ENTIDAD <> ''
)
select
  INSTITUCION,
  ENTIDAD_CD,
  MUNICIPIO,
  DECLARACION_ANIO,
  SUMA_VALOR_ADQUISICION,
  BIEN_INMUEBLE_VALOR,
  BIEN_MUEBLE_VALOR,
  VEHICULO_VALOR,
  TOTAL_DECLARACIONES, 
  PERCENT_INMUEBLE_VALOR,
  PERCENT_MUEBLE_VALOR,
  PERCENT_VEHICULO_VALOR
from add_normalize_entidad;
