DROP TABLE IF EXISTS nice-opus-462200-h0.ydata.R_1_DECLARACION_INGRESOS;

CREATE TABLE IF NOT EXISTS nice-opus-462200-h0.ydata.R_1_DECLARACION_INGRESOS AS
with ingresos_data as(
  select distinct 
    DECLARACION_ID,
    INSTITUCION,
    REMUNERACION_ANUAL_CARGO_PUBLICO,
    TOTAL_INGRESOS_MENSUALES_NETOS,
    INGRESO_ANUAL_NETO_DECLARANTE
  from nice-opus-462200-h0.ydata.C_S1_INGRESOS
  where REMUNERACION_ANUAL_CARGO_PUBLICO is not null 
  or TOTAL_INGRESOS_MENSUALES_NETOS is not null 
  or INGRESO_ANUAL_NETO_DECLARANTE is not null 
), declaracion_data as (
  select distinct
    DECLARACION_ID,
    INSTITUCION,
    FECHA_ACTUALIZACION,
    TIPO_DECLARACION,
    ES_COMPLETA,
    ACTUALIZACION_CONFLICTO_INTERES
  from nice-opus-462200-h0.ydata.C_S1_DECLARACION
), empleo_cargo_comision as (
  select distinct
  DECLARACION_ID,
  MUNICIPIO,
  ENTIDAD,
  from  nice-opus-462200-h0.ydata.C_S1_EMPLEO_CARGO_COMISION 
), t1 as (
SELECT
    bi.DECLARACION_ID,
    d.INSTITUCION,
    CASE
      WHEN UPPER(ecc.ENTIDAD) IN ('AGUASCALIENTES') THEN 'MX-AGU'
      WHEN UPPER(ecc.ENTIDAD) IN ('BAJA CALIFORNIA') THEN 'MX-BCN'
      WHEN UPPER(ecc.ENTIDAD) IN ('BAJA CALIFORNIA SUR') THEN 'MX-BCS'
      WHEN UPPER(ecc.ENTIDAD) IN ('CAMPECHE') THEN 'MX-CAM'
      WHEN UPPER(ecc.ENTIDAD) IN ('COAHUILA DE ZARAGOZA', 'COAHUILA') THEN 'MX-COA'
      WHEN UPPER(ecc.ENTIDAD) IN ('COLIMA') THEN 'MX-COL'
      WHEN UPPER(ecc.ENTIDAD) IN ('CHIAPAS') THEN 'MX-CHP'
      WHEN UPPER(ecc.ENTIDAD) IN ('CHIHUAHUA') THEN 'MX-CHH'
      WHEN UPPER(ecc.ENTIDAD) IN ('CIUDAD DE MEXICO','DISTRITO FEDERAL', 'CIUDAD DE MÉXICO') THEN 'MX-CMX'
      WHEN UPPER(ecc.ENTIDAD) IN ('DURANGO') THEN 'MX-DUR'
      WHEN UPPER(ecc.ENTIDAD) IN ('GUANAJUATO') THEN 'MX-GUA'
      WHEN UPPER(ecc.ENTIDAD) IN ('GUERRERO') THEN 'MX-GRO'
      WHEN UPPER(ecc.ENTIDAD) IN ('HIDALGO') THEN 'MX-HID'
      WHEN UPPER(ecc.ENTIDAD) IN ('JALISCO') THEN 'MX-JAL'
      WHEN UPPER(ecc.ENTIDAD) IN ('MEXICO','ESTADO DE MEXICO', 'MÉXICO', 'ESTADO DE MÈXICO', 'ESTADO DE MÉXICO') THEN 'MX-MEX'
      WHEN UPPER(ecc.ENTIDAD) IN ('MICHOACAN','MICHOACAN DE OCAMPO', 'MICHOACÁN DE OCAMPO') THEN 'MX-MIC'
      WHEN UPPER(ecc.ENTIDAD) IN ('MORELOS') THEN 'MX-MOR'
      WHEN UPPER(ecc.ENTIDAD) IN ('NAYARIT') THEN 'MX-NAY'
      WHEN UPPER(ecc.ENTIDAD) IN ('NUEVO LEON', 'NUEVO LEÓN') THEN 'MX-NLE'
      WHEN UPPER(ecc.ENTIDAD) IN ('OAXACA') THEN 'MX-OAX'
      WHEN UPPER(ecc.ENTIDAD) IN ('PUEBLA') THEN 'MX-PUE'
      WHEN UPPER(ecc.ENTIDAD) IN ('QUERETARO', 'QUERÉTARO') THEN 'MX-QUE'
      WHEN UPPER(ecc.ENTIDAD) IN ('QUINTANA ROO') THEN 'MX-ROO'
      WHEN UPPER(ecc.ENTIDAD) IN ('SAN LUIS POTOSI', 'SAN LUIS POTOSÍ') THEN 'MX-SLP'
      WHEN UPPER(ecc.ENTIDAD) IN ('SINALOA') THEN 'MX-SIN'
      WHEN UPPER(ecc.ENTIDAD) IN ('SONORA') THEN 'MX-SON'
      WHEN UPPER(ecc.ENTIDAD) IN ('TABASCO') THEN 'MX-TAB'
      WHEN UPPER(ecc.ENTIDAD) IN ('TAMAULIPAS') THEN 'MX-TAM'
      WHEN UPPER(ecc.ENTIDAD) IN ('TLAXCALA') THEN 'MX-TLA'
      WHEN UPPER(ecc.ENTIDAD) IN ('VERACRUZ','VERACRUZ DE IGNACIO DE LA LLAVE') THEN 'MX-VER'
      WHEN UPPER(ecc.ENTIDAD) IN ('YUCATAN', 'YUCATÁN') THEN 'MX-YUC'
      WHEN UPPER(ecc.ENTIDAD) IN ('ZACATECAS') THEN 'MX-ZAC'
        ELSE 'NO_APLICA'
    END AS ENTIDAD_CD,
    ecc.MUNICIPIO,
    EXTRACT(YEAR FROM d.FECHA_ACTUALIZACION) AS DECLARACION_ANIO,
    IFNULL(SAFE_CAST(bi.REMUNERACION_ANUAL_CARGO_PUBLICO AS NUMERIC), 0) AS REMUNERACION_ANUAL_CARGO_PUBLICO,
    IFNULL(SAFE_CAST(bi.TOTAL_INGRESOS_MENSUALES_NETOS AS NUMERIC), 0) AS TOTAL_INGRESOS_MENSUALES_NETOS,
    IFNULL(SAFE_CAST(bi.INGRESO_ANUAL_NETO_DECLARANTE AS NUMERIC), 0) AS INGRESO_ANUAL_NETO_DECLARANTE,
    ROW_NUMBER() OVER (
      PARTITION BY bi.DECLARACION_ID 
      ORDER BY d.FECHA_ACTUALIZACION DESC,
      d.TIPO_DECLARACION DESC,
      IFNULL(SAFE_CAST(bi.REMUNERACION_ANUAL_CARGO_PUBLICO AS NUMERIC), 0) DESC,
      IFNULL( SAFE_CAST(bi.TOTAL_INGRESOS_MENSUALES_NETOS AS NUMERIC), 0) DESC,
      IFNULL( SAFE_CAST(bi.INGRESO_ANUAL_NETO_DECLARANTE AS NUMERIC), 0) DESC
    ) AS rn
from ingresos_data AS bi 
join declaracion_data AS d
on bi.DECLARACION_ID = d.DECLARACION_ID
join empleo_cargo_comision ecc
on bi.DECLARACION_ID = ecc.DECLARACION_ID
)
select * from t1
WHERE
  t1.rn = 1;


