DROP TABLE IF EXISTS `nice-opus-462200-h0`.`ydata`.`AN_1_INSTITUCION_INGRESOS`;
CREATE TABLE IF NOT EXISTS `nice-opus-462200-h0`.`ydata`.`AN_1_INSTITUCION_INGRESOS` AS
  select 
  INSTITUCION,
  ENTIDAD_CD,
  MUNICIPIO,
  DECLARACION_ANIO,
  SUM(REMUNERACION_ANUAL_CARGO_PUBLICO) REMUNERACION_ANUAL_CARGO_PUBLICO,
  SUM(TOTAL_INGRESOS_MENSUALES_NETOS) TOTAL_INGRESOS_MENSUALES_NETOS,
  SUM(INGRESO_ANUAL_NETO_DECLARANTE) INGRESO_ANUAL_NETO_DECLARANTE
from nice-opus-462200-h0.ydata.R_1_DECLARACION_INGRESOS
group by 1,2,3,4
order by 1,2,3,4