drop table if exists nice-opus-462200-h0.ydata.R_1_DECLARACION_VALOR_ADQUISICION;

CREATE TABLE nice-opus-462200-h0.ydata.R_1_DECLARACION_VALOR_ADQUISICION AS
with bien_inmueble as (
  select distinct
  bi.DECLARACION_ID,
  first_value(ifnull(safe_cast(bi.VALOR_ADQUISICION as Numeric), 0))
    over(partition by bi.DECLARACION_ID order by d.FECHA_ACTUALIZACION desc, d.TIPO_DECLARACION, bi.VALOR_ADQUISICION desc) VALOR_ADQUISICION
  from nice-opus-462200-h0.ydata.C_S1_BIEN_INMUEBLE bi
  join nice-opus-462200-h0.ydata.C_S1_DECLARACION d
  on bi.DECLARACION_ID = d.DECLARACION_ID
  where safe_cast(bi.VALOR_ADQUISICION as Numeric) > 0
),bien_mueble as (
  select distinct
  bi.DECLARACION_ID,
  first_value(ifnull(safe_cast(bi.VALOR_ADQUISICION as Numeric), 0))
    over(partition by bi.DECLARACION_ID order by d.FECHA_ACTUALIZACION desc, d.TIPO_DECLARACION, bi.VALOR_ADQUISICION desc) VALOR_ADQUISICION
  from nice-opus-462200-h0.ydata.C_S1_BIEN_MUEBLE bi
  join nice-opus-462200-h0.ydata.C_S1_DECLARACION d
  on bi.DECLARACION_ID = d.DECLARACION_ID
  where safe_cast(bi.VALOR_ADQUISICION as Numeric) > 0
),vehiculo as (
  select distinct
  bi.DECLARACION_ID,
  first_value(ifnull(safe_cast(bi.VALOR_ADQUISICION as Numeric), 0))
    over(partition by bi.DECLARACION_ID order by d.FECHA_ACTUALIZACION desc, d.TIPO_DECLARACION, bi.VALOR_ADQUISICION desc) VALOR_ADQUISICION
  from nice-opus-462200-h0.ydata.C_S1_VEHICULO bi
  join nice-opus-462200-h0.ydata.C_S1_DECLARACION d
  on bi.DECLARACION_ID = d.DECLARACION_ID
  where safe_cast(bi.VALOR_ADQUISICION as Numeric) > 0
)
select distinct
d.DECLARACION_ID,
d.INSTITUCION,
CASE
  WHEN UPPER(ecc.ENTIDAD) IN ('AGUASCALIENTES') THEN 'MX-AGU'
  WHEN UPPER(ecc.ENTIDAD) IN ('BAJA CALIFORNIA') THEN 'MX-BCN'
  WHEN UPPER(ecc.ENTIDAD) IN ('BAJA CALIFORNIA SUR') THEN 'MX-BCS'
  WHEN UPPER(ecc.ENTIDAD) IN ('CAMPECHE') THEN 'MX-CAM'
  WHEN UPPER(ecc.ENTIDAD) IN ('COAHUILA DE ZARAGOZA', 'COAHUILA') THEN 'MX-COA'
  WHEN UPPER(ecc.ENTIDAD) IN ('COLIMA') THEN 'MX-COL'
  WHEN UPPER(ecc.ENTIDAD) IN ('CHIAPAS') THEN 'MX-CHP'
  WHEN UPPER(ecc.ENTIDAD) IN ('CHIHUAHUA') THEN 'MX-CHH'
  WHEN UPPER(ecc.ENTIDAD) IN ('CIUDAD DE MEXICO','DISTRITO FEDERAL', 'CIUDAD DE MÉXICO') THEN 'MX-CMX'
  WHEN UPPER(ecc.ENTIDAD) IN ('DURANGO') THEN 'MX-DUR'
  WHEN UPPER(ecc.ENTIDAD) IN ('GUANAJUATO') THEN 'MX-GUA'
  WHEN UPPER(ecc.ENTIDAD) IN ('GUERRERO') THEN 'MX-GRO'
  WHEN UPPER(ecc.ENTIDAD) IN ('HIDALGO') THEN 'MX-HID'
  WHEN UPPER(ecc.ENTIDAD) IN ('JALISCO') THEN 'MX-JAL'
  WHEN UPPER(ecc.ENTIDAD) IN ('MEXICO','ESTADO DE MEXICO', 'MÉXICO', 'ESTADO DE MÈXICO', 'ESTADO DE MÉXICO') THEN 'MX-MEX'
  WHEN UPPER(ecc.ENTIDAD) IN ('MICHOACAN','MICHOACAN DE OCAMPO', 'MICHOACÁN DE OCAMPO') THEN 'MX-MIC'
  WHEN UPPER(ecc.ENTIDAD) IN ('MORELOS') THEN 'MX-MOR'
  WHEN UPPER(ecc.ENTIDAD) IN ('NAYARIT') THEN 'MX-NAY'
  WHEN UPPER(ecc.ENTIDAD) IN ('NUEVO LEON', 'NUEVO LEÓN') THEN 'MX-NLE'
  WHEN UPPER(ecc.ENTIDAD) IN ('OAXACA') THEN 'MX-OAX'
  WHEN UPPER(ecc.ENTIDAD) IN ('PUEBLA') THEN 'MX-PUE'
  WHEN UPPER(ecc.ENTIDAD) IN ('QUERETARO', 'QUERÉTARO') THEN 'MX-QUE'
  WHEN UPPER(ecc.ENTIDAD) IN ('QUINTANA ROO') THEN 'MX-ROO'
  WHEN UPPER(ecc.ENTIDAD) IN ('SAN LUIS POTOSI', 'SAN LUIS POTOSÍ') THEN 'MX-SLP'
  WHEN UPPER(ecc.ENTIDAD) IN ('SINALOA') THEN 'MX-SIN'
  WHEN UPPER(ecc.ENTIDAD) IN ('SONORA') THEN 'MX-SON'
  WHEN UPPER(ecc.ENTIDAD) IN ('TABASCO') THEN 'MX-TAB'
  WHEN UPPER(ecc.ENTIDAD) IN ('TAMAULIPAS') THEN 'MX-TAM'
  WHEN UPPER(ecc.ENTIDAD) IN ('TLAXCALA') THEN 'MX-TLA'
  WHEN UPPER(ecc.ENTIDAD) IN ('VERACRUZ','VERACRUZ DE IGNACIO DE LA LLAVE') THEN 'MX-VER'
  WHEN UPPER(ecc.ENTIDAD) IN ('YUCATAN', 'YUCATÁN') THEN 'MX-YUC'
  WHEN UPPER(ecc.ENTIDAD) IN ('ZACATECAS') THEN 'MX-ZAC'
    ELSE 'NO_APLICA'
END AS ENTIDAD_CD,
ecc.MUNICIPIO,
extract(YEAR FROM d.FECHA_ACTUALIZACION) DECLARACION_ANIO,
(
  ifnull(bi.VALOR_ADQUISICION, 0) + 
  ifnull(bm.VALOR_ADQUISICION, 0) + 
  ifnull(v.VALOR_ADQUISICION, 0)
) SUMA_VALOR_ADQUISICION,
ifnull(bi.VALOR_ADQUISICION, 0) BIEN_INMUEBLE_VALOR,
ifnull(bm.VALOR_ADQUISICION, 0) BIEN_MUEBLE_VALOR,
ifnull(v.VALOR_ADQUISICION, 0) VEHICULO_VALOR
from nice-opus-462200-h0.ydata.C_S1_DECLARACION d
left join bien_inmueble bi
on d.DECLARACION_ID = bi.DECLARACION_ID
left join bien_mueble bm
on d.DECLARACION_ID = bm.DECLARACION_ID
left join vehiculo v
on d.DECLARACION_ID = v.DECLARACION_ID
join nice-opus-462200-h0.ydata.C_S1_EMPLEO_CARGO_COMISION ecc
on d.DECLARACION_ID = ecc.DECLARACION_ID