drop table if exists `nice-opus-462200-h0.ydata.AN_1_SERVIDORES_INDIVIDUALES_LLAVE`;

CREATE TABLE IF NOT EXISTS `nice-opus-462200-h0.ydata.AN_1_SERVIDORES_INDIVIDUALES_LLAVE`  AS
with CLEAN_COLUMNS as (
  SELECT
  IF(sp.SERVIDOR_PUBLICO_CURP IN ('None',''), NULL, sp.SERVIDOR_PUBLICO_CURP) AS CURP,
  IF(sp.NOMBRE IN ('None',''), NULL, sp.NOMBRE) AS NOMBRE,
  IF(sp.PRIMER_APELLIDO IN ('None',''), NULL, sp.PRIMER_APELLIDO) AS PRIMER_APELLIDO,
  IF(sp.SEGUNDO_APELLIDO IN ('None',''), NULL, sp.SEGUNDO_APELLIDO) AS SEGUNDO_APELLIDO,
  IF(sp.RFC_COMPLETO IN ('None',''), NULL, sp.RFC_COMPLETO) AS RFC_COMPLETO,
  IF(sp.CORREO_INSTITUCIONAL IN ('None',''), NULL, sp.CORREO_INSTITUCIONAL) AS CORREO_INSTITUCIONAL,
  IF(sp.CORREO_PERSONAL IN ('None',''), NULL, sp.CORREO_PERSONAL) AS CORREO_PERSONAL,
  IF(ecc.INSTITUCION IN ('None',''), NULL, ecc.INSTITUCION) AS INSTITUCION,
  IF(ecc.EMPLEO_CARGO_COMISION IN ('None',''), NULL, ecc.EMPLEO_CARGO_COMISION) AS EMPLEO_CARGO_COMISION,
  COUNT(DISTINCT sp.DECLARACION_ID) AS TOTAL_DECLARACIONES_DISTINTAS
FROM `nice-opus-462200-h0.ydata.C_S1_SERVIDOR_PUBLICO` sp
JOIN `nice-opus-462200-h0.ydata.C_S1_EMPLEO_CARGO_COMISION` ecc
  ON sp.DECLARACION_ID = ecc.DECLARACION_ID
GROUP BY
  CURP,
  NOMBRE,
  PRIMER_APELLIDO,
  SEGUNDO_APELLIDO,
  RFC_COMPLETO,
  CORREO_INSTITUCIONAL,
  CORREO_PERSONAL,
  INSTITUCION,
  EMPLEO_CARGO_COMISION
)
SELECT * FROM CLEAN_COLUMNS
WHERE CURP IS NOT NULL
OR (
  NOMBRE IS NOT NULL
  AND PRIMER_APELLIDO IS NOT NULL
  AND SEGUNDO_APELLIDO IS NOT NULL
)
OR RFC_COMPLETO IS NOT NULL
OR CORREO_INSTITUCIONAL IS NOT NULL
OR CORREO_PERSONAL IS NOT NULL;




